name: Test Build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3.1.0

    - name: Build
      run: go build -v .

